services:

  redis-server: # Add this for debugging
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure

   
  client:
    image: "shaneyboy/movies-client-static"
    mem_limit: 128m
    hostname: "client"

  movies-nginx:
    restart: always
    # image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - api
      - client

  api:
    image: movies-api:latest
    build:
      context: ../../../../               # <-- include repo root so Directory.Packages.props is available
      dockerfile: Apps/Movies/Movies.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    # ports:
    #   - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PgDb=${ConnectionStrings__PgDb}
      - ConnectionStrings__SqlDb=${ConnectionStrings__SqlDb}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - AllowedOrigins__0=${AllowedOrigins__0}
      - AllowedOrigins__1=${AllowedOrigins__1}
      - AllowedOrigins__2=${AllowedOrigins__2}
      - AllowedOrigins__3=${AllowedOrigins__3}
      - AllowedOrigins__4=${AllowedOrigins__4}
      - AllowedOrigins__5=${AllowedOrigins__5}
      - AllowedOrigins__6=${AllowedOrigins__6}
      - AllowedOrigins__7=${AllowedOrigins__7}
      - APP_UID=${APP_UID}
      # - ASPNETCORE_URLS=http://+:8080;https://+:8081
