services:
  movies-api: 
    image: shaneyboy/movies-api:latest
    ports:
      - "80:8080"
    environment:
      - ConnectionStrings__PgDb=${ConnectionStrings__PgDb}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - APP_UID=${APP_UID}
      
  redis-server: 
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure